// UpgradeLab V38 Cloudflare Pages Worker: exact Market.CSGO bulk prices + Steam Market confirmation.
const H={'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-methods':'GET,OPTIONS','cache-control':'public, max-age=1800'};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const canon=v=>String(v||'').normalize('NFKC').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
function values(raw){if(Array.isArray(raw))return raw;if(Array.isArray(raw?.items))return raw.items;if(raw?.items&&typeof raw.items==='object')return Object.values(raw.items);if(Array.isArray(raw?.data))return raw.data;if(raw?.data&&typeof raw.data==='object')return Object.values(raw.data);return []}
function parseMarket(raw){const best=new Map();for(const x of values(raw)){const name=canon(x?.market_hash_name||x?.marketHashName||x?.name);const price=Number(x?.price_usd??x?.price??x?.min_price??0);if(!name||!Number.isFinite(price)||price<=0)continue;const old=best.get(name);if(old==null||price<old)best.set(name,price)}return [...best].map(([market_hash_name,price])=>({market_hash_name,price:Math.round(price*1000)/1000}))}
async function marketCsgo(){const r=await fetch('https://market.csgo.com/api/v2/prices/USD.json',{headers:{Accept:'application/json'},cf:{cacheEverything:true,cacheTtl:1800}});if(!r.ok)throw new Error('Market.CSGO '+r.status);const raw=await r.json();const items=parseMarket(raw);if(!items.length)throw new Error('Market.CSGO returned no prices');return items}
function parseUsd(text=''){const raw=String(text).replace(/\s/g,'').replace(/[^0-9.,]/g,'');if(!raw)return 0;const c=raw.lastIndexOf(','),d=raw.lastIndexOf('.');const n=Number(c>d?raw.replace(/\./g,'').replace(',','.'):raw.replace(/,/g,''));return Number.isFinite(n)?n:0}
export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:H});const u=new URL(request.url);
 if(u.pathname==='/api/prices'){try{return json({items:await marketCsgo(),source:'Market.CSGO USD — точное совпадение',currency:'USD'})}catch(e){return json({items:[],source:'рынок временно недоступен',error:String(e)},200)}}
 if(u.pathname==='/api/steam-price'){const name=canon(u.searchParams.get('market_hash_name'));if(!name)return json({success:false},400);try{const p=new URL('https://steamcommunity.com/market/priceoverview/');p.searchParams.set('appid','730');p.searchParams.set('currency','1');p.searchParams.set('market_hash_name',name);const r=await fetch(p,{cf:{cacheEverything:true,cacheTtl:1800}});const d=await r.json();const price=parseUsd(d.median_price||d.lowest_price);return price>0?json({success:true,price_usd:price,source:'Steam Market USD median/lowest'}):json({success:false},404)}catch(e){return json({success:false,error:String(e)},502)}}
 return env.ASSETS.fetch(request)}};