import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, sendPasswordResetEmail } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { getFirestore, doc, getDoc, onSnapshot, collection, query, orderBy, limit, getDocs } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import { getFunctions, httpsCallable } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-functions.js';
import { firebaseConfig } from './firebase-config.js';

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),functions=getFunctions(app,'us-central1');
const fn={bootstrap:httpsCallable(functions,'bootstrapUser'),upgrade:httpsCallable(functions,'startUpgrade'),sell:httpsCallable(functions,'sellItems'),nick:httpsCallable(functions,'setNickname')};
const APIS=['https://raw.githubusercontent.com/ByMykel/CSGO-API/main/public/api/en/skins.json','https://cdn.jsdelivr.net/gh/ByMykel/CSGO-API@main/public/api/en/skins.json'];
const rates={USD:1,EUR:.92,UAH:41.4,RUB:87},symbols={USD:'$',EUR:'€',UAH:'₴',RUB:'₽'},HOUSE=.90,MAX_CHANCE=80;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let user=null,userDoc=null,profile=null,skins=[],inventory=[],history=[],target=null,sourceItems=[],selected=new Set(),shown=48,spin=false,currency=localStorage.getItem('ul-currency')||'UAH',fast=localStorage.getItem('ul-fast')==='1',sound=localStorage.getItem('ul-sound')!=='0',unsubs=[];
const toast=t=>{const e=$('#toast');e.textContent=t;e.className='show';setTimeout(()=>e.className='',2400)};
const fmt=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:currency==='USD'||currency==='EUR'?2:0,minimumFractionDigits:currency==='USD'||currency==='EUR'?2:0}).format((Number(v)||0)*rates[currency])+' '+symbols[currency];
const priceFor=(name,rarity)=>{let h=0;for(const c of name)h=(h*31+c.charCodeAt(0))>>>0;const base={consumer:1.2,industrial:3,'mil-spec':9,restricted:28,classified:95,covert:420,contraband:2500,extraordinary:900}[rarity]||12;return Math.max(.2,Math.round(base*(.65+(h%160)/100)*100)/100)};
function rarityOf(x){return String(x.rarity?.id||x.rarity?.name||'').toLowerCase().replace('_','-')}
function avatarLetter(n){return (n||'U').trim().charAt(0).toUpperCase()||'U'}
function setAuthMode(register){$('#nickname').hidden=!register;$('#authTitle').textContent=register?'Регистрация':'Вход';$('#authSubmit').textContent=register?'Создать аккаунт':'Войти';$('#loginTab').className=register?'ghost':'upgrade-btn';$('#registerTab').className=register?'upgrade-btn':'ghost';$('#authForm').dataset.mode=register?'register':'login'}
$('#loginTab').onclick=()=>setAuthMode(false);$('#registerTab').onclick=()=>setAuthMode(true);setAuthMode(false);
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='';try{const email=$('#email').value.trim(),pass=$('#password').value;if(e.currentTarget.dataset.mode==='register'){const cred=await createUserWithEmailAndPassword(auth,email,pass);await fn.bootstrap({nickname:$('#nickname').value.trim()||'Игрок'});toast('Аккаунт создан')}else await signInWithEmailAndPassword(auth,email,pass)}catch(err){$('#authError').textContent=humanError(err)}};
$('#resetPassword').onclick=async()=>{try{await sendPasswordResetEmail(auth,$('#email').value.trim());toast('Письмо для сброса отправлено')}catch(e){$('#authError').textContent=humanError(e)}};
$('#logoutBtn').onclick=()=>signOut(auth);
function humanError(e){const c=e?.code||'';if(c.includes('invalid-credential'))return 'Неверный email или пароль';if(c.includes('email-already-in-use'))return 'Этот email уже используется';if(c.includes('weak-password'))return 'Пароль должен быть минимум 6 символов';if(c.includes('too-many-requests'))return 'Слишком много попыток. Попробуй позже';return e?.message||'Ошибка'}

onAuthStateChanged(auth,async u=>{unsubs.forEach(x=>x());unsubs=[];user=u;target=null;sourceItems=[];if(!u){$('#authScreen').classList.remove('hidden');return}$('#authScreen').classList.add('hidden');try{await fn.bootstrap({nickname:'Игрок'})}catch{}subscribeUser();subscribeFeed();await loadCatalog()});
function subscribeUser(){unsubs.push(onSnapshot(doc(db,'users',user.uid),s=>{userDoc=s.data()||{};inventory=Array.isArray(userDoc.inventory)?userDoc.inventory:[];history=Array.isArray(userDoc.history)?userDoc.history:[];renderAll();const op=userDoc.lastOperation;if(op?.unseen){$('#pendingBanner').classList.add('show');showOutcome(op.result)}else $('#pendingBanner').classList.remove('show')}));unsubs.push(onSnapshot(doc(db,'profiles',user.uid),s=>{profile=s.data()||{};renderProfile();renderTop()}))}
function subscribeFeed(){const q=query(collection(db,'feed'),orderBy('createdAt','desc'),limit(30));unsubs.push(onSnapshot(q,s=>{$('#feedList').innerHTML=s.docs.map(d=>{const x=d.data();return `<div class="feed-item" data-uid="${x.uid}"><img src="${x.image||''}"><div><b>${esc(x.nickname||'Игрок')}</b><span>${esc(x.itemName||'Скин')}</span><span>${Number(x.chance||0).toFixed(2)}%</span></div></div>`}).join('')||'<p class="muted">Пока пусто</p>';$$('.feed-item').forEach(e=>e.onclick=()=>openPublicProfile(e.dataset.uid))}))}
async function openPublicProfile(uid){const s=await getDoc(doc(db,'profiles',uid));if(!s.exists())return toast('Профиль не найден');const p=s.data();$('#publicProfile').innerHTML=`<div class="profile-head"><div class="avatar">${avatarLetter(p.nickname)}</div><div><h2>${esc(p.nickname||'Игрок')}</h2><p class="muted">Публичный профиль</p></div></div><div class="stats-grid"><div class="stat"><b>${p.stats?.spins||0}</b><small>апгрейдов</small></div><div class="stat"><b>${p.stats?.wins||0}</b><small>побед</small></div><div class="stat"><b>${p.stats?.losses||0}</b><small>поражений</small></div><div class="stat"><b>${fmt(p.stats?.bestWinUSD||0)}</b><small>лучший выигрыш</small></div></div>`;open('publicProfileModal')}
async function loadCatalog(){if(skins.length)return;for(const url of APIS){try{const r=await fetch(url);if(!r.ok)throw 0;const raw=await r.json();skins=raw.filter(x=>x.image&&x.name).map((x,i)=>{const rarity=rarityOf(x),wear=x.wears?.[0]?.name||'Field-Tested',name=x.name.includes('|')?x.name:`${x.weapon?.name||'Skin'} | ${x.name}`;return {id:String(x.id||i),name,wear,image:x.image,rarity,category:String(x.category?.name||x.weapon?.name||'').toLowerCase().includes('knife')?'knife':String(x.category?.name||'').toLowerCase().includes('glove')?'glove':'weapon',priceUSD:priceFor(name,rarity)}});break}catch{}}$('#status').textContent=skins.length?`${skins.length} предметов. Сервер проверяет ставку и результат.`:'Каталог не загрузился';renderCatalog()}
function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function card(x,mode='catalog'){return `<article class="skin-card rarity-${esc(x.rarity||'mil-spec')}" data-id="${esc(x.id||x.uid)}"><div class="skin-img"><img src="${esc(x.image)}" loading="lazy"></div><h3>${esc(x.name)}</h3><small>${esc(x.wear||'')}</small><b>${fmt(x.priceUSD)}</b>${mode==='catalog'?'<button class="upgrade-btn choose">В апгрейд</button>':mode==='inventory'?'<div class="card-actions"><button class="ghost use">Поставить</button><button class="ghost sell">Продать</button></div>':'<button class="ghost pick">Выбрать</button>'}</article>`}
function filtered(){let q=$('#search').value.toLowerCase(),c=$('#category').value,a=skins.filter(x=>(c==='all'||x.category===c)&&x.name.toLowerCase().includes(q));const sort=$('#sort').value;a.sort((x,y)=>sort==='priceDesc'?y.priceUSD-x.priceUSD:sort==='name'?x.name.localeCompare(y.name):x.priceUSD-y.priceUSD);return a}
function renderCatalog(){$('#skinGrid').innerHTML=filtered().slice(0,shown).map(x=>card(x)).join('');$$('#skinGrid .skin-card').forEach(e=>e.querySelector('.choose').onclick=()=>{target=skins.find(x=>String(x.id)===String(e.dataset.id));syncUpgrade();scrollTo({top:0,behavior:'smooth'})})}
function renderInventory(){$('#inventoryGrid').innerHTML=inventory.map(x=>card(x,'inventory')).join('')||'<div class="empty-state">Инвентарь пуст</div>';$$('#inventoryGrid .skin-card').forEach(e=>{const x=inventory.find(x=>String(x.uid)===String(e.dataset.id));e.querySelector('.use').onclick=()=>{sourceItems=[x];showPage('upgrade');syncUpgrade()};e.querySelector('.sell').onclick=()=>sellItems([x.uid])});renderPicker()}
function renderPicker(){$('#modalGrid').innerHTML=inventory.map(x=>card(x,'picker')).join('')||'<div class="empty-state">Инвентарь пуст</div>';$$('#modalGrid .skin-card').forEach(e=>{const id=e.dataset.id;e.classList.toggle('selected',selected.has(id));e.querySelector('.pick').onclick=()=>{selected.has(id)?selected.delete(id):selected.add(id);renderPicker()}})}
function stakeUSD(){if(sourceItems.length)return sourceItems.reduce((a,x)=>a+Number(x.priceUSD||0),0);const v=Number($('#stake')?.value||0);return v/rates[currency]}
function chance(){if(!target)return 0;return Math.min(MAX_CHANCE,stakeUSD()/target.priceUSD*100*HOUSE)}
function renderSource(){const el=$('#sourceSlot');if(sourceItems.length){el.className='item-slot';el.innerHTML=sourceItems.slice(0,3).map(x=>`<div class="mini-source"><img src="${x.image}"><span>${esc(x.name)}</span></div>`).join('')+`<b>${fmt(stakeUSD())}</b>`}else{el.className='item-slot cash';const current=$('#stake')?.value||'';el.innerHTML=`<div class="cash-entry"><span>${symbols[currency]}</span><label>Сумма ставки<input id="stake" type="text" inputmode="decimal" value="${current}" placeholder="0"></label><em>Введи любую сумму полностью</em></div>`;$('#stake').oninput=syncUpgrade}}
function renderTarget(){const el=$('#targetSlot');if(!target){el.className='item-slot empty';el.innerHTML='<span>Нажми на скин ниже</span>';return}el.className='item-slot';el.innerHTML=`<img src="${target.image}"><h3>${esc(target.name)}</h3><small>${esc(target.wear)}</small><b>${fmt(target.priceUSD)}</b>`}
function syncUpgrade(){renderSource();renderTarget();const c=chance(),v=stakeUSD();$('#chance').textContent=c.toFixed(2)+'%';$('#multi').textContent=target&&v>0?'x'+(target.priceUSD/v).toFixed(2):'x0.00';$('#winArc').style.setProperty('--chance',`${c*3.6}deg`);$('#upgradeBtn').disabled=spin||!target||v<=0||c<=0||c>MAX_CHANCE||(!sourceItems.length&&v>Number(userDoc?.balanceUSD||0));$('#result').textContent=!target?'Выбери целевой скин':c>=MAX_CHANCE?'Выбери более дорогой скин: максимум 80%':'Готово к апгрейду'}
async function startUpgrade(){if(spin||$('#upgradeBtn').disabled)return;spin=true;syncUpgrade();$('#result').textContent='Сервер проверяет ставку…';const requestId=crypto.randomUUID();try{const payload={requestId,target:{id:target.id,name:target.name,image:target.image,wear:target.wear,rarity:target.rarity,priceUSD:target.priceUSD},sourceItemIds:sourceItems.map(x=>x.uid),cashUSD:sourceItems.length?0:stakeUSD()};const res=await fn.upgrade(payload);await animateWheel(res.data.result);showOutcome(res.data.result);sourceItems=[];selected.clear()}catch(e){toast(humanError(e));$('#result').textContent='Апгрейд не выполнен'}finally{spin=false;syncUpgrade()}}
async function animateWheel(r){const d=fast?1800:6500,turns=fast?4:10,final=r.angle??Math.random()*360,n=$('#needle');n.getAnimations().forEach(a=>a.cancel());if(sound)beep(110,.08);const a=n.animate([{transform:'rotate(0deg)'},{transform:`rotate(${turns*360+final}deg)`}],{duration:d,easing:'cubic-bezier(.12,.02,.08,1)',fill:'forwards'});await a.finished;if(sound)resultSound(r.win)}
function showOutcome(r){if(!r)return;$('#result').innerHTML=r.win?`<strong class="win">ВЫИГРЫШ — ${esc(r.target?.name||'скин')}</strong>`:`<strong class="lose">ПРОИГРЫШ</strong>`;target=r.target||target;renderTarget()}
function beep(freq=.1,d=.1){try{const C=window.AudioContext||window.webkitAudioContext,c=new C,o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.stop(c.currentTime+d)}catch{}}
function resultSound(win){if(!sound)return;[0,.11,.22].forEach((t,i)=>setTimeout(()=>beep(win?[440,660,880][i]:[220,180,140][i],.15),t*1000))}
async function sellItems(ids){try{await fn.sell({itemIds:ids});toast('Продано')}catch(e){toast(humanError(e))}}
function renderHistory(){$('#historyList').innerHTML=history.map(h=>`<article class="history-card"><div class="history-side">${h.sources?.length?h.sources.map(x=>`<div class="hist-item"><img src="${x.image}"><span>${esc(x.name)}</span><b>${fmt(x.priceUSD)}</b></div>`).join(''):`<div class="hist-cash"><b>${fmt(h.cashUSD||0)}</b><small>ставка</small></div>`}</div><div class="history-arrow">⌃</div><div class="history-side"><div class="hist-item"><img src="${h.target?.image||''}"><span>${esc(h.target?.name||'')}</span><b>${fmt(h.target?.priceUSD||0)}</b></div></div><div class="history-meta"><b>${Number(h.chance||0).toFixed(2)}%</b><strong class="${h.win?'win':'lose'}">${h.win?'Win':'Lose'}</strong></div></article>`).join('')||'<div class="empty-state">История пуста</div>'}
function renderTop(){if(!userDoc)return;$('#balance').textContent=fmt(userDoc.balanceUSD||0);$('#invCount').textContent=inventory.length;$('#currency').value=currency;const n=profile?.nickname||'Игрок';$('#topNick').textContent=n;$('#topAvatar').textContent=avatarLetter(n);$('#soundQuick').textContent=sound?'🔊':'🔇';$('#fastQuick').classList.toggle('active',fast)}
function renderProfile(){if(!profile||!user)return;const n=profile.nickname||'Игрок',st=profile.stats||{};$('#profileNick').textContent=n;$('#profileAvatar').textContent=avatarLetter(n);$('#profileUid').textContent='ID профиля: '+user.uid.slice(0,8);$('#nickInput').value=n;$('#statsGrid').innerHTML=`<div class="stat"><b>${st.spins||0}</b><small>апгрейдов</small></div><div class="stat"><b>${st.wins||0}</b><small>побед</small></div><div class="stat"><b>${st.losses||0}</b><small>поражений</small></div><div class="stat"><b>${fmt(st.bestWinUSD||0)}</b><small>лучший выигрыш</small></div>`}
function renderAll(){renderTop();renderInventory();renderHistory();renderProfile();syncUpgrade()}
function pickByRatio(m){const v=stakeUSD();if(v<=0)return toast('Сначала введи ставку');target=skins.filter(x=>x.priceUSD>v).sort((a,b)=>Math.abs(a.priceUSD-v*m)-Math.abs(b.priceUSD-v*m))[0]||null;syncUpgrade()}
function pickByChance(p){const v=stakeUSD();if(v<=0)return toast('Сначала введи ставку');const wanted=v*100*HOUSE/p;target=skins.slice().sort((a,b)=>Math.abs(a.priceUSD-wanted)-Math.abs(b.priceUSD-wanted))[0]||null;syncUpgrade()}
function showPage(id){$$('.nav,.page').forEach(x=>x.classList.remove('active'));$(`.nav[data-page="${id}"]`)?.classList.add('active');$('#'+id).classList.add('active')}
function open(id){$('#'+id).classList.remove('hidden')}function close(id){$('#'+id).classList.add('hidden')}
$$('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$$('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));$('#currency').onchange=e=>{currency=e.target.value;localStorage.setItem('ul-currency',currency);renderAll();renderCatalog()};$('#search').oninput=()=>{shown=48;renderCatalog()};$('#category').onchange=renderCatalog;$('#sort').onchange=renderCatalog;$('#more').onclick=()=>{shown+=48;renderCatalog()};$('#clearTarget').onclick=()=>{target=null;syncUpgrade()};$('#clearSource').onclick=()=>{sourceItems=[];selected.clear();syncUpgrade()};$('#sourceMode').onclick=()=>{sourceItems=[];selected.clear();syncUpgrade()};$('#chooseInventory').onclick=()=>{selected=new Set(sourceItems.map(x=>String(x.uid)));renderPicker();open('modal')};$('#applySources').onclick=()=>{sourceItems=inventory.filter(x=>selected.has(String(x.uid)));close('modal');syncUpgrade()};$('#upgradeBtn').onclick=startUpgrade;$('#autoTarget').onclick=()=>pickByRatio(2);$$('.quick button').forEach(b=>b.onclick=()=>b.dataset.m?pickByRatio(+b.dataset.m):pickByChance(+b.dataset.p));$('#sellAll').onclick=()=>inventory.length?sellItems(inventory.map(x=>x.uid)):toast('Инвентарь пуст');$('#soundQuick').onclick=()=>{sound=!sound;localStorage.setItem('ul-sound',sound?'1':'0');renderTop()};$('#fastQuick').onclick=()=>{fast=!fast;localStorage.setItem('ul-fast',fast?'1':'0');renderTop()};$('#saveNick').onclick=async()=>{try{await fn.nick({nickname:$('#nickInput').value.trim()});toast('Ник сохранён')}catch(e){toast(humanError(e))}};
